### ISSUE TITLE
That one.  Yep.  That one.  

### ISSUE THREAD

**Issue by faddat** [hypriot/hypriot-talks#2]
https://github.com/hypriot/hypriot-talks/blob/master/20160210-Docker-Meetup-Belguim/docker_pirates_cluster_lab_node-style.png

**Comment by MathiasRenner** [comment]
@faddat :-) I guess you took part in the meetup yesterday and couldn't wait to talk with Dieter about the hypriot cluster lab? This is an issue, indeed  :-D

**Comment by faddat** [comment]
Oh, nope!  I simply thought that the graphic was great.  I really do wish I could make it out to one of your meetups, though.  I am just starting to use github issues very liberally overall.  It's the only interactivity on the platform other than pull requests, and "awesome pic"! Doesn't seem like a good pull request...

**Comment by MathiasRenner** [comment]
Ah, I see! Thank you :-) 
For all types of kind words, you can always leave a message below our blog posts (for the Hypriot Cluster Lab, it is [this one](http://blog.hypriot.com/post/introducing-hypriot-cluster-lab-docker-clustering-as-easy-as-it-gets/)) or in the [gitter channel](https://gitter.im/hypriot/talk). We welcome and follow up any feedback.
Looking forward to reading smth from you soon!
